### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by TerryDev** [mohinparamasivam/GitLab-11.4.7-Authenticated-Remote-Code-Execution#2]
e

**Comment by TerryDev** [comment]
Ok... for some reason I'm not getting this error anymore. Instead I'm getting this 
```
Traceback (most recent call last):
  File "49263.py", line 196, in <module>
    response1 = request.post(gitlab_url+'/projects',data=payload,cookies=cookies,proxies=proxies,headers=headers,verify=False)
  File "/usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl/requests/sessions.py", line 578, in post
  File "/usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl/requests/sessions.py", line 530, in request
  File "/usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl/requests/sessions.py", line 643, in send
  File "/usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl/requests/adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://target:5080/projects (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35d2ebef10>: Failed to establish a new connection: [Errno 111] Connection refused',)))
```

**Comment by mohinparamasivam** [comment]
@TerryDev  Managed to fix this issue?. This issue is caused when u don't have a session so most probably ur login is invalid or maybe the server has already been reset. Sign Up a new user and try with new creds. Cheers!

**Comment by TerryDev** [comment]
>  or maybe the server has already been reset.


This was it lol, forgot this could happen :P

**Comment by TerryDev** [comment]
opening this again, the `AttributeError: 'NoneType' object has no attribute 'get'` error is showing again.
